# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods

	pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :branch => 'google-io-codelabs-2018'
	pod 'Alamofire', '4.8.1'
	pod 'CryptoSwift'
	pod 'IQKeyboardManagerSwift'
	pod 'Fabric'
pod 'BigInt'
pod 'Crashlytics'
end

target 'TestDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

shared_pods

  # Pods for TestDemoApp

  target 'TestDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDemoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

