# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


target 'TestDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

	pod 'MaterialComponents'
	pod 'Alamofire', '4.8.1'
	pod 'CryptoSwift'
	pod 'IQKeyboardManagerSwift'
	pod 'Fabric'
	pod 'BigInt'
	pod 'Crashlytics'


  # Pods for TestDemoApp

  target 'TestDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDemoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

