# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OstSdk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FMDB'
  pod 'CryptoSwift'
  pod 'BigInt'
pod 'BigNumber', :git => 'https://github.com/mkrd/Swift-Big-Integer.git'

  # Pods for OstSdk

  target 'OstSdkTests' do
    inherit! :search_paths
    # Pods for testing
 pod 'FMDB'
  end

end
